config/routes.rb
GreenReview::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'users#index'

  resources :products do
    resources :reviews
  end
  resources :ratings, only: [:create, :update]
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ProductImagesUploader

  has_many :reviews
  has_many :ratings, dependent: :destroy
  has_many :raters, through: :ratings, source: :users
  belongs_to :user

  accepts_nested_attributes_for :reviews

  validates :title, presence: true
  validates :description, presence: true

  def self.search(search)
    if search
      where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  validates :user, presence: true
  validates :product, presence: true
  validates :stars, presence: true

  belongs_to :user
  belongs_to :product
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :description, presence: true
  validates :product, presence: true
  validates :user, presence: true

  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  has_many :reviews
  has_many :products, dependent: :nullify

  has_many :ratings, dependent: :destroy
  has_many :rated_products, through: :ratings, source: :products


  def is_admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def after_sign_in_path_for(resource)
    products_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation)}
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    @review = @product.reviews.build
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to products_path
      flash[:notice] = "Successfully added product"
    else
      render new_product_path
    end
  end

  def index
    @products = Product.search(params[:search])
    @ratings = Rating.where(user: current_user)
    render layout: 'index'
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render action: 'edit'
    end
  end

  def product_params
    params.require(:product).permit(:title, :description, :image, :user_id)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
  @rating = Rating.new(rating_params)
    respond_to do |format|
      if @rating.save
        format.json { render json: @rating, status: :created }
      else
        flash[:error] = "Your rating may not have been saved"
      end
    end
  end

  def update
    @rating = Rating.find_by(user: current_user, product_id: rating_params[:product_id])
    respond_to do |format|
      if @rating.update(rating_params)
        format.json { render json: @rating, status: :created }
      else
        flash[:error] = "Your rating may not have been updated"
      end
    end
  end

  private
  def rating_params
    params.require(:rating).permit(:product_id, :stars).merge(user: current_user)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.build
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.build(review_params)
    if @review.save
      redirect_to product_path(@product)
      flash[:notice] = 'Review has been added'
      ProductReview.review_notification(@review).deliver
    else
      render 'new'
    end
  end

  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    redirect_to product_reviews
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def rating(user, value, product)
    user_rating = product.ratings.where(user: user).take || ''

    if user_rating.blank?
      user_rating_id = ''
    else
      user_rating_id = user_rating.id
    end
    star_id = "product_#{product.id}_#{value}"

    if user_rating.blank? || value > user_rating.stars
      star_class = "fa fa-star-o star"
    else
      star_class = "fa fa-star star"
    end

    content_tag(:a, "",
      class: star_class,
      id: star_id,
      value: value,
      data: {
        product_id: product.id,
        user_rating_id: user_rating_id
        }
      )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Green Reviews</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render '/shared/header' %>
    <div class="small-6 large-centered columns text-center">
     <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Green Reviews</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= form_tag products_path, :method => 'get', :id => "products_search" do %>
     <%= yield %>
    <% end %>
   </div>
   <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/product_review/review_notification.text.erb
<%= "Your product #{@review.product.title} was reviewed by #{@review.user.username}" %>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :title, label: 'Title' %>
  <%= f.input :description, label: 'Description' %>
  <%= f.file_field :image, label: 'Upload Product Image' %>
  <%= f.button :submit, "Add Product" %>
<% end %>

app/views/products/_header.html.erb
<nav class="top-bar" data-topbar>
  <section class="top-bar-section">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Green Reviews', products_path %></h1>
      </li>
      <li class="has-form">
        <div class="row collapse">
          <div class="large-8 small-9 columns">
            <%= text_field_tag :search, params[:search], placeholder: 'Find Products' %>
          </div>
          <div class="large-4 small-3 columns">
             <%= submit_tag "Search", :title => nil, class: 'alert button expand' %>
          </div>
        </div>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>
  </section>

  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
      <li><%= link_to 'All Products', products_path %></li>
      <li><%= link_to 'Add a New Product', new_product_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: "delete" %></li>
      <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/products/_products.html.erb
<% @products.each do |product| %>

  <div class="row products">
    <%= image_tag product.image %>
  </div>

  <div class="row products">

    <% (1..5).each do |i| %>
      <%= rating(current_user, i, product) %>
    <% end %>
  </div>

  <div class="row products">
    <%= product.title %> -
    <%= product.description %>
  </div>

  <div class='button radius tiny index_buttons' >
    <%= link_to 'Review this Product', new_product_review_path(product.id) %>
  </div>

  <div class='button radius tiny index_buttons'>
    <%= link_to 'View Product Reviews', product_path(product.id) %>
  </div>

<% end %>

app/views/products/index.html.erb
<%= render partial: 'header' %>

<div class="small-6 large-centered columns text-center">

  <h1>Green Products</h1>

  <%= render partial: 'products' %>

</div>

app/views/products/new.html.erb
<%= render "form" %>

app/views/products/products.js.erb
$("#products").html("<%= escape_javascript(render("/products/products")) %>");

app/views/products/show.html.erb
<br><br>
  <h3> <%= @product.title %><h3>
  <h6><%= @product.description %></h6><br>
  <div><%= image_tag @product.image %></div><br>
  <% @reviews.each do |review| %>
        <p class="text-left"><strong><%= review.user.username %></strong> - <em><%= review.title %></em><br>
    <%= review.description %><p>
<% end %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <h3><%= review.title %></h3>
  <%= review.description %>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@product, @review] do |f| %>
  <%= f.input :title, required: false %>
  <%= f.input :description, required: true %>
  <%= f.hidden_field :user_id, value: "#{current_user.id}" %>
  <%= f.button :submit, "Submit Review" %>

<% end %>

app/views/reviews/show.html.erb
<h3><%= @review.title %></h3>
<%= @review.description %>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Green Reviews', products_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to 'All Products', products_path %></li>
        <li><%= link_to 'Add a New Product', new_product_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </section>
</nav>